// <auto-generated />
using System;
using Flowaccount.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210526081637_addTypeToCategories")]
    partial class addTypeToCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flowaccount.Data.Models.Transactions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancialType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(23,8)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 62076m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19937m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 74315m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 31102m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77883m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7822m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 75767m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 566m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 44204m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 35912m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 55607m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 46086m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 42200m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 75230m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 79145m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3824m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 13056m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78781m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 58871m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 45495m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 44449m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20259m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 23919m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 47829m
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 72654m
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 66365m
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 66569m
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 29798m
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64148m
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 32172m
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 38596m
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 27399m
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 22444m
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4616m
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 9816m
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 33458m
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 68502m
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 60683m
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19164m
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 24000m
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5275m
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 4296m
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 24370m
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 36479m
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3566m
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 51654m
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 14655m
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 43890m
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 60555m
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 35268m
                        },
                        new
                        {
                            Id = 51L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 9910m
                        },
                        new
                        {
                            Id = 52L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 14180m
                        },
                        new
                        {
                            Id = 53L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 51982m
                        },
                        new
                        {
                            Id = 54L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 24602m
                        },
                        new
                        {
                            Id = 55L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78797m
                        },
                        new
                        {
                            Id = 56L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 22252m
                        },
                        new
                        {
                            Id = 57L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 23417m
                        },
                        new
                        {
                            Id = 58L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 35572m
                        },
                        new
                        {
                            Id = 59L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 802m
                        },
                        new
                        {
                            Id = 60L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 34038m
                        },
                        new
                        {
                            Id = 61L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78645m
                        },
                        new
                        {
                            Id = 62L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 23096m
                        },
                        new
                        {
                            Id = 63L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 61945m
                        },
                        new
                        {
                            Id = 64L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 67472m
                        },
                        new
                        {
                            Id = 65L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 8362m
                        },
                        new
                        {
                            Id = 66L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20555m
                        },
                        new
                        {
                            Id = 67L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 25803m
                        },
                        new
                        {
                            Id = 68L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 57141m
                        },
                        new
                        {
                            Id = 69L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 68033m
                        },
                        new
                        {
                            Id = 70L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 43988m
                        },
                        new
                        {
                            Id = 71L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 13945m
                        },
                        new
                        {
                            Id = 72L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 35578m
                        },
                        new
                        {
                            Id = 73L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 75256m
                        },
                        new
                        {
                            Id = 74L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 14675m
                        },
                        new
                        {
                            Id = 75L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 27734m
                        },
                        new
                        {
                            Id = 76L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 22655m
                        },
                        new
                        {
                            Id = 77L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 43254m
                        },
                        new
                        {
                            Id = 78L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 66514m
                        },
                        new
                        {
                            Id = 79L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 3267m
                        },
                        new
                        {
                            Id = 80L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64705m
                        },
                        new
                        {
                            Id = 81L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 40029m
                        },
                        new
                        {
                            Id = 82L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 54158m
                        },
                        new
                        {
                            Id = 83L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 17532m
                        },
                        new
                        {
                            Id = 84L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 73300m
                        },
                        new
                        {
                            Id = 85L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 71615m
                        },
                        new
                        {
                            Id = 86L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 66708m
                        },
                        new
                        {
                            Id = 87L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 49238m
                        },
                        new
                        {
                            Id = 88L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 54148m
                        },
                        new
                        {
                            Id = 89L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 45053m
                        },
                        new
                        {
                            Id = 90L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 48374m
                        },
                        new
                        {
                            Id = 91L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 15682m
                        },
                        new
                        {
                            Id = 92L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 61757m
                        },
                        new
                        {
                            Id = 93L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 68830m
                        },
                        new
                        {
                            Id = 94L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7125m
                        },
                        new
                        {
                            Id = 95L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 60707m
                        },
                        new
                        {
                            Id = 96L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 22060m
                        },
                        new
                        {
                            Id = 97L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 13364m
                        },
                        new
                        {
                            Id = 98L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 17149m
                        },
                        new
                        {
                            Id = 99L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77876m
                        },
                        new
                        {
                            Id = 100L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 9904m
                        });
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 6, 8, 17, 16, 37, 442, DateTimeKind.Local).AddTicks(4219),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 6, 10, 17, 16, 37, 442, DateTimeKind.Local).AddTicks(4219),
                            Name = "ถูกหวย"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 6, 4, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5225),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 6, 8, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5225),
                            Name = "เงินเดือน"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 6, 7, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5309),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 6, 11, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5309),
                            Name = "แม่ให้"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 6, 12, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5313),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 6, 13, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5313),
                            Name = "ปล้นพี่เสก"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2021, 6, 10, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5315),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 6, 11, 17, 16, 37, 443, DateTimeKind.Local).AddTicks(5315),
                            Name = "อาหาร"
                        });
                });

            modelBuilder.Entity("Flowaccount.Data.Models.Transactions", b =>
                {
                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
