// <auto-generated />
using System;
using Flowaccount.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210326111407_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flowaccount.Data.Models.TransactionModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(23,8)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 52011m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 15064m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 36987m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 46894m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 55039m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 75686m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 56667m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 46563m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 72373m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 61226m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 38462m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 71937m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 8440m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 10372m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 64612m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 5339m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 13597m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 43199m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 31680m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 63302m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 8443m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 18385m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 42860m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 61080m
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 46883m
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 38460m
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 18640m
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 68340m
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 13157m
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 73138m
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 1430m
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 74582m
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 17271m
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 65535m
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 11211m
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 66292m
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 21739m
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 43701m
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 52519m
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 33148m
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 36444m
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 9838m
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 75312m
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 64461m
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 44833m
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 57362m
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 34374m
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 68578m
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 2675m
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 64889m
                        },
                        new
                        {
                            Id = 51L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 699m
                        },
                        new
                        {
                            Id = 52L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 34338m
                        },
                        new
                        {
                            Id = 53L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 64986m
                        },
                        new
                        {
                            Id = 54L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 29308m
                        },
                        new
                        {
                            Id = 55L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 62687m
                        },
                        new
                        {
                            Id = 56L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 71351m
                        },
                        new
                        {
                            Id = 57L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 75514m
                        },
                        new
                        {
                            Id = 58L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 61832m
                        },
                        new
                        {
                            Id = 59L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 27059m
                        },
                        new
                        {
                            Id = 60L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 72653m
                        },
                        new
                        {
                            Id = 61L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 71729m
                        },
                        new
                        {
                            Id = 62L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 55910m
                        },
                        new
                        {
                            Id = 63L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 13632m
                        },
                        new
                        {
                            Id = 64L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 3580m
                        },
                        new
                        {
                            Id = 65L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 76816m
                        },
                        new
                        {
                            Id = 66L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 33489m
                        },
                        new
                        {
                            Id = 67L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 4146m
                        },
                        new
                        {
                            Id = 68L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 33560m
                        },
                        new
                        {
                            Id = 69L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 73091m
                        },
                        new
                        {
                            Id = 70L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 32916m
                        },
                        new
                        {
                            Id = 71L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 23931m
                        },
                        new
                        {
                            Id = 72L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 23133m
                        },
                        new
                        {
                            Id = 73L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 48945m
                        },
                        new
                        {
                            Id = 74L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 42066m
                        },
                        new
                        {
                            Id = 75L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 46115m
                        },
                        new
                        {
                            Id = 76L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 69823m
                        },
                        new
                        {
                            Id = 77L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 41898m
                        },
                        new
                        {
                            Id = 78L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 46268m
                        },
                        new
                        {
                            Id = 79L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 26470m
                        },
                        new
                        {
                            Id = 80L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 68928m
                        },
                        new
                        {
                            Id = 81L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 75167m
                        },
                        new
                        {
                            Id = 82L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 31420m
                        },
                        new
                        {
                            Id = 83L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 10337m
                        },
                        new
                        {
                            Id = 84L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 35131m
                        },
                        new
                        {
                            Id = 85L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 67609m
                        },
                        new
                        {
                            Id = 86L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 42553m
                        },
                        new
                        {
                            Id = 87L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 67065m
                        },
                        new
                        {
                            Id = 88L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 7137m
                        },
                        new
                        {
                            Id = 89L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 42079m
                        },
                        new
                        {
                            Id = 90L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 44945m
                        },
                        new
                        {
                            Id = 91L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 50962m
                        },
                        new
                        {
                            Id = 92L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 14280m
                        },
                        new
                        {
                            Id = 93L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 7599m
                        },
                        new
                        {
                            Id = 94L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 33066m
                        },
                        new
                        {
                            Id = 95L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 43235m
                        },
                        new
                        {
                            Id = 96L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 22548m
                        },
                        new
                        {
                            Id = 97L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 18679m
                        },
                        new
                        {
                            Id = 98L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 3,
                            Value = 10451m
                        },
                        new
                        {
                            Id = 99L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 25796m
                        },
                        new
                        {
                            Id = 100L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 1,
                            Value = 3760m
                        });
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 4, 8, 18, 14, 7, 15, DateTimeKind.Local).AddTicks(3530),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 11, 18, 14, 7, 15, DateTimeKind.Local).AddTicks(3530),
                            Name = "ถูกหวย"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 4, 6, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(810),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 7, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(810),
                            Name = "เงินเดือน"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 3, 30, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(890),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 3, 31, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(890),
                            Name = "แม่ให้"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 3, 28, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(890),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 3, 29, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(890),
                            Name = "ปล้นพี่เสก"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2021, 3, 30, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(890),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 1, 18, 14, 7, 24, DateTimeKind.Local).AddTicks(890),
                            Name = "อาหาร"
                        });
                });

            modelBuilder.Entity("Flowaccount.Data.Models.TransactionModel", b =>
                {
                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
