// <auto-generated />
using System;
using Flowaccount.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flowaccount.Data.Models.Transactions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinancialType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(23,8)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 61849m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 67203m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64552m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5071m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 25511m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 42487m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 71394m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 67062m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 72281m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 55761m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 62338m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 8440m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64370m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 44551m
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 65981m
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 37227m
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 44432m
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2935m
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 47197m
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20655m
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 28141m
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 50237m
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 29404m
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 9661m
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 75857m
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 73966m
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 75380m
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 29459m
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 53440m
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 16269m
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78591m
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19545m
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 72878m
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 27658m
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 76025m
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 33257m
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 50301m
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78672m
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 65753m
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 50966m
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 28671m
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 27173m
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78248m
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 17393m
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 54582m
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7374m
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 57212m
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 7649m
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 15078m
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 10340m
                        },
                        new
                        {
                            Id = 51L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 21833m
                        },
                        new
                        {
                            Id = 52L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 47143m
                        },
                        new
                        {
                            Id = 53L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 69316m
                        },
                        new
                        {
                            Id = 54L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 11448m
                        },
                        new
                        {
                            Id = 55L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 69796m
                        },
                        new
                        {
                            Id = 56L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 19783m
                        },
                        new
                        {
                            Id = 57L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 49168m
                        },
                        new
                        {
                            Id = 58L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64205m
                        },
                        new
                        {
                            Id = 59L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 34209m
                        },
                        new
                        {
                            Id = 60L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 47880m
                        },
                        new
                        {
                            Id = 61L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 73694m
                        },
                        new
                        {
                            Id = 62L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1169m
                        },
                        new
                        {
                            Id = 63L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 49327m
                        },
                        new
                        {
                            Id = 64L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 13512m
                        },
                        new
                        {
                            Id = 65L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 26667m
                        },
                        new
                        {
                            Id = 66L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 55452m
                        },
                        new
                        {
                            Id = 67L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 18215m
                        },
                        new
                        {
                            Id = 68L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 40771m
                        },
                        new
                        {
                            Id = 69L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 70713m
                        },
                        new
                        {
                            Id = 70L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 20459m
                        },
                        new
                        {
                            Id = 71L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 5371m
                        },
                        new
                        {
                            Id = 72L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 21080m
                        },
                        new
                        {
                            Id = 73L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 47153m
                        },
                        new
                        {
                            Id = 74L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 56799m
                        },
                        new
                        {
                            Id = 75L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 45151m
                        },
                        new
                        {
                            Id = 76L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64589m
                        },
                        new
                        {
                            Id = 77L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 820m
                        },
                        new
                        {
                            Id = 78L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 72788m
                        },
                        new
                        {
                            Id = 79L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 853m
                        },
                        new
                        {
                            Id = 80L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินข้าว",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 25833m
                        },
                        new
                        {
                            Id = 81L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1941m
                        },
                        new
                        {
                            Id = 82L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 13200m
                        },
                        new
                        {
                            Id = 83L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 37461m
                        },
                        new
                        {
                            Id = 84L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ถูกหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 70678m
                        },
                        new
                        {
                            Id = 85L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 33243m
                        },
                        new
                        {
                            Id = 86L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 39381m
                        },
                        new
                        {
                            Id = 87L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 49736m
                        },
                        new
                        {
                            Id = 88L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 42004m
                        },
                        new
                        {
                            Id = 89L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 64574m
                        },
                        new
                        {
                            Id = 90L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 27620m
                        },
                        new
                        {
                            Id = 91L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 2112m
                        },
                        new
                        {
                            Id = 92L,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2019, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เก็บเงินได้",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 15055m
                        },
                        new
                        {
                            Id = 93L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 60167m
                        },
                        new
                        {
                            Id = 94L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 39631m
                        },
                        new
                        {
                            Id = 95L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 1657m
                        },
                        new
                        {
                            Id = 96L,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2018, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ปันผล",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 43274m
                        },
                        new
                        {
                            Id = 97L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 1,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "เงินเดือน",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 71780m
                        },
                        new
                        {
                            Id = 98L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "กินเหล้า",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 36956m
                        },
                        new
                        {
                            Id = 99L,
                            CategoryId = 4,
                            CreatedOn = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 78095m
                        },
                        new
                        {
                            Id = 100L,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinancialType = 3,
                            IsDelete = false,
                            ModifiedOn = new DateTime(2018, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "ซื้อหวย",
                            Status = 0,
                            TransactionDate = new DateTime(2018, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Value = 77350m
                        });
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2021, 4, 14, 18, 29, 53, 73, DateTimeKind.Local).AddTicks(1310),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 16, 18, 29, 53, 73, DateTimeKind.Local).AddTicks(1310),
                            Name = "ถูกหวย"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2021, 4, 13, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6710),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 16, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6710),
                            Name = "เงินเดือน"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTime(2021, 4, 13, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6790),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 15, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6790),
                            Name = "แม่ให้"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTime(2021, 3, 31, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6800),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 4, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6800),
                            Name = "ปล้นพี่เสก"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTime(2021, 4, 5, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6800),
                            IsDelete = false,
                            ModifiedOn = new DateTime(2021, 4, 7, 18, 29, 53, 82, DateTimeKind.Local).AddTicks(6800),
                            Name = "อาหาร"
                        });
                });

            modelBuilder.Entity("Flowaccount.Data.Models.Transactions", b =>
                {
                    b.HasOne("api.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("api.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
